In [1]:
import pandas as pd

In [2]:
url ="https://raw.githubusercontent.com/Jose-guerra2002/etl-data-pipeline2510832022/refs/heads/main/data/raw/D_departamentos.csv"
df = pd.read_csv(url)
df.head()

  id_departamento departamento   ubicacion
0             D10          TI   Edificio A
1             D11     Finanzas      Remoto
2             D12         RRHH  Edificio A
3             D13       Ventas  Edificio A
4             D14      Compras  Edificio A

In [3]:
df.shape
df.columns
df.info()
df.isnull().sum()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9 entries, 0 to 8
Data columns (total 3 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   id_departamento  9 non-null      object
 1   departamento     9 non-null      object
 2   ubicacion        9 non-null      object
dtypes: object(3)
memory usage: 348.0+ bytes

id_departamento    0
departamento       0
ubicacion          0
dtype: int64

In [4]:
def limpiar_datos(df):
      df = df.copy()
      df.columns = df.columns.str.strip().str.lower()
      for col in df.select_dtypes(include='object'):
          df[col] = df[col].astype(str).str.strip()
      print("DataFrame limpio:")
      display(df.head())
      print(df.info())
      return df
departamentos = limpiar_datos(df)

DataFrame limpio:

  id_departamento departamento   ubicacion
0             D10           TI  Edificio A
1             D11     Finanzas      Remoto
2             D12         RRHH  Edificio A
3             D13       Ventas  Edificio A
4             D14      Compras  Edificio A

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9 entries, 0 to 8
Data columns (total 3 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   id_departamento  9 non-null      object
 1   departamento     9 non-null      object
 2   ubicacion        9 non-null      object
dtypes: object(3)
memory usage: 348.0+ bytes
None

In [5]:
def limpiar_duplicados(df):
      df = df.copy()
      df = df.drop_duplicates()
      print("Shape sin duplicados:")
      print(df.shape)
      return df
departamentos = limpiar_duplicados(departamentos)

Shape sin duplicados:
(8, 3)

In [6]:
def filtrar_validos(df):
      validos = df.dropna(subset=['id_departamento', 'departamento',
   'ubicacion']).copy()
      print("Datos validos:")
      display(validos.head())
      print(validos.shape)
      return validos
validos_departamentos = filtrar_validos(departamentos)

Datos validos:

  id_departamento departamento   ubicacion
0             D10           TI  Edificio A
1             D11     Finanzas      Remoto
2             D12         RRHH  Edificio A
3             D13       Ventas  Edificio A
4             D14      Compras  Edificio A

(8, 3)

In [8]:
def identificar_rechazo(df):
      rechazados = df[df[['id_departamento', 'departamento',
  'ubicacion']].isnull().any(axis=1)].copy()
      rechazados['motivo_rechazo'] = rechazados.apply(
          lambda x: 'Falta id_departamento' if
  pd.isnull(x['id_departamento'])
          else 'Falta departamento' if pd.isnull(x['departamento'])
          else 'Falta ubicacion' if pd.isnull(x['ubicacion'])
          else 'Otro',
          axis=1
      )
      print("Datos rechazados:")
      display(rechazados.head())
      print(rechazados.shape)
      return rechazados
      rechazados_departamentos = identificar_rechazo(departamentos)

In [15]:
rechazados_departamentos = pd.DataFrame()

In [16]:
def exportar_departamentos(validos, rechazados):
      validos.to_csv("D_departamentos_curated.csv", index=False)
      rechazados.to_csv("D_departamentos_rejects.csv", index=False)
      print("Archivos exportados:")
      print("- D_departamentos_curated.csv")
      print("- D_departamentos_rejects.csv")

exportar_departamentos(validos_departamentos,
rechazados_departamentos)

Archivos exportados:
- D_departamentos_curated.csv
- D_departamentos_rejects.csv

In [17]:
!pip install sqlalchemy psycopg2-binary

Requirement already satisfied: sqlalchemy in /usr/local/lib/python3.12/dist-packages (2.0.48)
Collecting psycopg2-binary
  Downloading psycopg2_binary-2.9.11-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.whl.metadata (4.9 kB)
Requirement already satisfied: greenlet>=1 in /usr/local/lib/python3.12/dist-packages (from sqlalchemy) (3.3.2)
Requirement already satisfied: typing-extensions>=4.6.0 in /usr/local/lib/python3.12/dist-packages (from sqlalchemy) (4.15.0)
Downloading psycopg2_binary-2.9.11-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.whl (4.2 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 4.2/4.2 MB 90.2 MB/s eta 0:00:00
Installing collected packages: psycopg2-binary
Successfully installed psycopg2-binary-2.9.11

In [18]:
from sqlalchemy import create_engine
import pandas as pd

In [19]:
database_url = "postgresql://etl_seguros_6rdr_user:BLDMfhhALJNiooAJN3zJErFDUwEYk7xM@dpg-d6quauh5pdvs73bhia4g-a.virginia-postgres.render.com/etl_seguros_6rdr"

In [20]:
engine = create_engine(database_url)

In [23]:
test = pd.read_sql("SELECT 1", engine)
print(test)

   ?column?
0         1

In [24]:
validos_departamentos.to_sql(
      'd_departamentos_curated',
      engine,
      if_exists='replace',
      index=False
  )

8

In [25]:
rechazados_departamentos.to_sql(
      'd_departamentos_rejects',
      engine,
      if_exists='replace',
      index=False
  )

0

In [26]:
pd.read_sql("SELECT * FROM d_departamentos_curated LIMIT 10",
  engine)

  id_departamento departamento   ubicacion
0             D10           TI  Edificio A
1             D11     Finanzas      Remoto
2             D12         RRHH  Edificio A
3             D13       Ventas  Edificio A
4             D14      Compras  Edificio A
5             D15    Logística      Remoto
6             D16    Auditoría  Edificio A
7             D17    Marketing      Remoto